### ISSUE TITLE
Crash with "Cannot call method 'wrtieHead' of undefined"

### ISSUE THREAD

**Issue by evil-shrike** [hayes/unpm#73]
Hi.
I'm experiencing the following error sometimes:
```bash
TypeError: Cannot call method 'wrtieHead' of undefined
    at Request.proxy.Response [as _callback] (/usr/lib/node_modules/unpm/lib/controllers/getPackage.js:59:17)
    at Request.self.callback (/usr/lib/node_modules/unpm/node_modules/request/request.js:373:22)
    at Request.emit (events.js:98:17_
    at Request.<anonymous> (/usr/lib/node_modules/unpm/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/unpm/node_modules/request/request.js:1266:12)
    at IncomingMessage.enum (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```
unpm is behind our corporate proxy (passwordless). It's specified globally. 

The error happened in different circumstances. But currently it happens when trying to install a not-existing package like:
```
npm install -g @myco/generator-notexists
```

The worst thing is that unpm terminates on the error.

**Comment by hayes** [comment]
hey, since I did not get a reply from you I am hoping this is working for you.  I am going to close this for now, but leave a comment if you are still having issues, and I will reopen it.
